name: Bug Report
description: Report a bug or unexpected behavior in Career Reality Checker
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    label: Description
    attributes:
      placeholder: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    label: Steps to Reproduce
    attributes:
      placeholder: |
        1. Go to '...'
        2. Enter '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    label: Version
    attributes:
      placeholder: 0.1.0
  - type: textarea
    id: additional
    label: Additional Context
    attributes:
      placeholder: Screenshots, browser info, etc.

