name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    label: Problem Statement
    attributes:
      placeholder: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    label: Proposed Solution
    attributes:
      placeholder: How should this work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    label: Alternatives Considered
    attributes:
      placeholder: Other approaches you've considered
  - type: textarea
    id: context
    label: Additional Context
    attributes:
      placeholder: Any other relevant information

